name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 혹은 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          mkdir -p public
          cp -r front/public/* public/
          git config user.name "sora"
          git config user.email "ju22hy@gmail.com"
          git add public
          git commit -m "Deploy to GitHub Pages"
          git push origin `git subtree split --prefix public main`:gh-pages --force
